name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scans every day at 2 AM UTC
    - cron: '0 2 * * *'

# Permissions needed for security scanning
permissions:
  contents: read
  security-events: write
  actions: read
  id-token: write

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './go.mod'

    - name: Run Microsoft Security DevOps
      uses: microsoft/security-devops-action@v1
      id: msdo
      with:
        categories: 'code,dependencies,containers,IaC'
        tools: 'bandit,binskim,eslint,templateanalyzer,terrascan,trivy'
      continue-on-error: true

    - name: Upload MSDO SARIF results to GitHub
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
      continue-on-error: true
